spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://product-mysql:3306/bezkoder_db
    username: root
    password: 123456

  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  rabbitmq:
    host: rabbitmq
    port: 5672

routing-key:
  product: product_key
  price: price_key

queue:
  product: product_queue
  price: price_queue

xchange:
  name: exchange_rpc

server:
  port: 8083